### ISSUE TITLE
Extend all the examples

### ISSUE THREAD

**Issue by b1ron** [FerretDB/dance#530]
This is to unify all examples and also add more commands for more coverage.

```[tasklist]
### Tasks
- [ ] https://github.com/FerretDB/dotnet-example/pull/5
- [ ] https://github.com/FerretDB/java-example/pull/3
- [ ] https://github.com/FerretDB/python-example/pull/2
```

**Comment by AlekSi** [comment]
#554 is not merged and actually fails

**Comment by b1ron** [comment]
I have reverted FerretDB/java-example/pull/4.

If the database exists and you run the `dropDatabase` command the result differs depending on whether the database [exists or not](https://github.com/FerretDB/FerretDB/blob/36ce153cd313996826ba8492f6b58cfe2849bc07/internal/handlers/pg/msg_dropdatabase.go#L64-L65). MongoDB just returns `{ "ok" : 1 }` regardless. I must have created the test database leading me to create FerretDB/java-example/pull/4.

```sh
byron@byron-ThinkCentre-M910q:~/workdir/dance$ mongo --quiet --eval 'db.runCommand({dropDatabase: 1});'
{ "ok" : 1 }
byron@byron-ThinkCentre-M910q:~/workdir/dance$ mongo --quiet --eval 'db.foo.insert({}); db.runCommand({dropDatabase: 1});'
{ "dropped" : "test", "ok" : 1 }
```
