### ISSUE TITLE
Investigate Meteor errors

### ISSUE THREAD

**Issue by b1ron** [FerretDB/dance#632]
Use proxy mode to uncover more future errors.

```[tasklist]
### Tasks
- [x] MongoServerSelectionError - fixed by setting `directConnection=true` in `MONGO_OPLOG_URL`
- [x] MongoServerError (FieldPath field names may not start with '$') - fixed in https://github.com/FerretDB/FerretDB/issues/3638
- [x] when the oplog is detected it will open a tailable cursor with awaitData true https://github.com/FerretDB/FerretDB/issues/2283
- [x] it uses a deprecated command `oplogReplay` in conjunction with a filter on `ts` to replay oplog entries
- [x] seems to be optional https://github.com/FerretDB/FerretDB/issues/2984
- [x] FailedToParse -"find: unknown field \"$clusterTime\"" https://github.com/FerretDB/FerretDB/issues/3667
```

**Comment by b1ron** [comment]
re 4.

> Deprecated
> 
> Changed in version 4.4.
> 
> Starting in MongoDB 4.4, the oplogReplay field is deprecated. find fields that use the [$gte](https://www.mongodb.com/docs/manual/reference/operator/aggregation/gte/#mongodb-expression-exp.-gte), [$gt](https://www.mongodb.com/docs/manual/reference/operator/aggregation/gt/#mongodb-expression-exp.-gt), or [$eq](https://www.mongodb.com/docs/manual/reference/operator/aggregation/eq/#mongodb-expression-exp.-eq) filter predicated on the ts field will automatically utilize the storage format of the [replica set's oplog](https://www.mongodb.com/docs/manual/core/replica-set-oplog/#std-label-replica-set-oplog) to execute the command more efficiently. If specified, the server accepts the oplogReplay flag for backwards compatibility, but the flag has no effect.
