### ISSUE TITLE
Investigate Meteor oplog test failures

### ISSUE THREAD

**Issue by b1ron** [FerretDB/dance#728]
Refs FerretDB/FerretDB/pull/3925

One just times out and one returns `$natural sort for non-capped collection is not supported.`

Needs more investigation.

```[tasklist]
### Tasks
- [ ] https://github.com/FerretDB/dance/blob/main/tests/meteor-oplog-cursor-supported.sh
- [ ] https://github.com/FerretDB/dance/blob/main/tests/meteor-oplog-entry-skipping.sh
- [ ] https://github.com/FerretDB/dance/blob/main/tests/meteor-oplog-x-implicit-collection-creation.sh
```

**Comment by rumyantseva** [comment]
@b1ron did you create oplog collection manually? Something like `db.createCollection("oplog.rs", {capped: true, size: 1024000})`. FerretDB doesn't create oplog collection automatically, so you can see this error in case `oplog` was created as a regular collection, not a capped collection.

**Comment by b1ron** [comment]
@rumyantseva yes I did created the oplog before running the tests, still seeing failures. I will do some more investigation.
