### ISSUE TITLE
Add flags to enable strict stable API

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/dance#791]
Our examples for .NET, Python and Java should accept `-strict` or `--strict` (whatever is easier) boolean flag that would enable strict Stable API.

We should use appropriate standard libraries for those languages for flags / arguments parsing, not accept "raw" CLI parameters directly (i.e., in Python, we should use [`argparse module`](https://docs.python.org/3/library/argparse.html) instead of accessing `sys.argv` directly).
```[tasklist]
### Tasks
- [ ] allow enabling of strict API for .NET example
- [ ] allow enabling of strict API for Java example
- [x] allow enabling of strict API for Python example
```

Dance CI changes are not in scope.
